### ISSUE TITLE
Camera intrinsics and time stamp

### ISSUE THREAD

**Issue by lan-creator** [ai4ce/EgoPAT3Dv2#1]
Hello, thank you for your great work. And I wonder if there are camera intrinsics and real time stamp corresponding to the color images, thank you.

**Comment by bugreator** [comment]
For the camera intrinsic info, you can refer to line 361 in [eval.py](https://github.com/ai4ce/EgoPAT3Dv2/blob/main/eval.py) . Since the videos were recorded in 30fps, you can get the time stamp with the frame index of each frame.

**Comment by lan-creator** [comment]
This is really helpful. Thank you for your reply.
